#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
CHECKLIST_FILE="$ROOT_DIR/docs/chrome-mv3-manual-acceptance.md"
RESULTS_FILE="$ROOT_DIR/docs/chrome-mv3-manual-acceptance-results.md"
RUN_AT=$(date '+%Y-%m-%d %H:%M:%S %Z')
FAILURES=0
SKIPS=0

if [[ ! -f "$CHECKLIST_FILE" ]]; then
  printf 'Checklist not found: %s\n' "$CHECKLIST_FILE" >&2
  exit 1
fi

mark_checkbox() {
  local label="$1" tmp
  tmp=$(mktemp)
  awk -v target="$label" '
    $0 == "- [ ] " target { print "- [x] " target; next }
    { print }
  ' "$CHECKLIST_FILE" > "$tmp"
  mv "$tmp" "$CHECKLIST_FILE"
}

log_result() {
  local result="$1" label="$2" detail="${3:-}"
  printf -- '- %s: %s%s\n' "$result" "$label" "${detail:+. $detail}" >> "$RESULTS_FILE"
}

read_result() {
  local prompt="$1" reply
  while true; do
    printf '  %s?%s %s [p=pass, f=fail, s=skip] ' "$YELLOW" "$RESET" "$prompt"
    read -r reply || true
    case "$reply" in
      p|P) REPLY_RESULT="pass"; return ;;
      f|F) REPLY_RESULT="fail"; return ;;
      s|S) REPLY_RESULT="skip"; return ;;
      *) warn "enter p, f, or s" ;;
    esac
  done
}

record_check() {
  local label="$1" prompt="${2:-$1}"
  read_result "$prompt"
  case "$REPLY_RESULT" in
    pass) mark_checkbox "$label"; log_result PASS "$label" ;;
    fail) FAILURES=$((FAILURES + 1)); log_result FAIL "$label" ;;
    skip) SKIPS=$((SKIPS + 1)); log_result SKIP "$label" ;;
  esac
}

collect_batch_check() {
  local flag_name="$1" label="$2" variant="$3"
  read_result "$label"
  log_result "${REPLY_RESULT^^}" "$variant: $label"
  if [[ "$REPLY_RESULT" != "pass" ]]; then
    printf -v "$flag_name" '%s' 0
    if [[ "$REPLY_RESULT" == "fail" ]]; then
      FAILURES=$((FAILURES + 1))
    else
      SKIPS=$((SKIPS + 1))
    fi
  fi
}

finalize_batch_check() {
  local flag="$1" label="$2"
  if [[ "$flag" -eq 1 ]]; then
    mark_checkbox "$label"
  fi
}

count_open_before_completion() {
  awk '
    /^## Completion/ { exit }
    /^- \[ \]/ { count++ }
    END { print count + 0 }
  ' "$CHECKLIST_FILE"
}

cat >> "$RESULTS_FILE" <<EOF

## Run $RUN_AT

EOF

banner "DevRecall Chrome MV3 acceptance"

stage "Production preflight"
say "Use the Chrome profile where dist/ is loaded as an unpacked extension."
open_url "chrome://extensions"
step "Reload DevRecall on chrome://extensions so this run uses the production build just created."
step "Open DevRecall Options, the side panel, and DevTools Network. Filter requests by api.openai.com."
step "Keep the API key in Chrome. Do not paste it into this wizard."
open_url "chrome://version"
ask CHROME_VERSION "Chrome version shown at chrome://version:"
printf -- '- Chrome: %s\n' "${CHROME_VERSION:-not recorded}" >> "$RESULTS_FILE"
pause "Press Enter after the extension and request log are ready."

batch_request_ok=1
batch_no_later_ok=1
batch_unsent_ok=1
batch_canceled_ok=1

stage "Bulk enrichment, switch to Local-only"
step "In Local-only, save at least three readable pages and confirm they show Saved locally."
step "Switch to Hybrid, click Add AI features to local pages, verify the confirmation count, and confirm."
step "As soon as the first OpenAI request is in flight, switch to Local-only. Wait for the progress panel to settle."
collect_batch_check batch_request_ok "The request already sent may finish." "Bulk enrichment, mode switch"
collect_batch_check batch_no_later_ok "No later tagging, embedding, or retry request is sent." "Bulk enrichment, mode switch"
collect_batch_check batch_unsent_ok "Unsent pages remain `keyword_ready` without an enrichment error." "Bulk enrichment, mode switch"
collect_batch_check batch_canceled_ok "Progress reports the operation as canceled, not failed." "Bulk enrichment, mode switch"

stage "Semantic re-index, switch to Local-only"
step "Prepare at least three semantic re-index candidates. Options must show Re-index semantic search (3 or more)."
step "Switch to Hybrid, verify the confirmation count, then start Re-index semantic search."
step "As soon as the first embeddings request is in flight, switch to Local-only. Wait for progress to settle."
collect_batch_check batch_request_ok "The request already sent may finish." "Semantic re-index, mode switch"
collect_batch_check batch_no_later_ok "No later tagging, embedding, or retry request is sent." "Semantic re-index, mode switch"
collect_batch_check batch_unsent_ok "Unsent pages remain `keyword_ready` without an enrichment error." "Semantic re-index, mode switch"
collect_batch_check batch_canceled_ok "Progress reports the operation as canceled, not failed." "Semantic re-index, mode switch"

stage "Cancel confirmed batches"
step "Prepare another batch of at least three pages. Start bulk Add AI features and press Cancel while the first request is in flight."
collect_batch_check batch_request_ok "The request already sent may finish." "Bulk enrichment, Cancel button"
collect_batch_check batch_no_later_ok "No later tagging, embedding, or retry request is sent." "Bulk enrichment, Cancel button"
collect_batch_check batch_unsent_ok "Unsent pages remain `keyword_ready` without an enrichment error." "Bulk enrichment, Cancel button"
collect_batch_check batch_canceled_ok "Progress reports the operation as canceled, not failed." "Bulk enrichment, Cancel button"
step "Prepare another semantic batch. Start Re-index semantic search and press Cancel while the first request is in flight."
collect_batch_check batch_request_ok "The request already sent may finish." "Semantic re-index, Cancel button"
collect_batch_check batch_no_later_ok "No later tagging, embedding, or retry request is sent." "Semantic re-index, Cancel button"
collect_batch_check batch_unsent_ok "Unsent pages remain `keyword_ready` without an enrichment error." "Semantic re-index, Cancel button"
collect_batch_check batch_canceled_ok "Progress reports the operation as canceled, not failed." "Semantic re-index, Cancel button"
finalize_batch_check "$batch_request_ok" "The request already sent may finish."
finalize_batch_check "$batch_no_later_ok" "No later tagging, embedding, or retry request is sent."
finalize_batch_check "$batch_unsent_ok" 'Unsent pages remain `keyword_ready` without an enrichment error.'
finalize_batch_check "$batch_canceled_ok" "Progress reports the operation as canceled, not failed."

stage "Auto-save in both modes"
step "Enable auto-save. In Hybrid, open a new allowlisted page such as developer.mozilla.org and stay for at least 35 seconds."
record_check 'The page saves locally before enrichment starts.'
record_check 'The page can progress from `keyword_ready` to `ready`.'
step "Switch to Local-only. Open a different allowlisted page and stay for at least 35 seconds."
record_check 'The page stops at `keyword_ready`.'
record_check 'No OpenAI request is sent.' "No OpenAI request was sent for the Local-only auto-save."
step "In both modes, spend at least 35 seconds on a non-allowlisted page that has not already been saved."
record_check 'Auto-save does not capture the page.'

stage "Remove and restore the API key"
step "Store Hybrid as the preference and make sure at least one page is ready with summary, tags, classification, and embeddings."
step "Click Remove API key, read the confirmation, and click Remove key."
record_check 'Effective mode becomes Local-only while the stored Hybrid preference remains.'
record_check 'Saved pages, summaries, tags, classifications, and embeddings remain available.'
record_check 'Automatic capture and search send no OpenAI requests.'
record_check 'Per-page AI actions remain visible but disabled with a Settings link.'
step "Save the valid key again without changing the stored search-mode preference."
record_check 'Effective mode returns to Hybrid without rewriting the stored preference.'
record_check 'Existing page data remains unchanged.'

stage "Search mode and fallback"
step "In Local-only, search for a term that matches saved pages in several lifecycle states."
record_check 'Results use BM25 and the completed search reports `Local-only`.'
record_check 'Results may include `keyword_ready`, `enriching`, and `ready` pages.'
step "In Hybrid with the valid key, run a different uncached query and inspect Network."
record_check 'The completed search reports `Hybrid`.'
record_check 'OpenAI receives one query-embedding request unless a cached result is used.'
step "Make only the embeddings request fail, then run another different query. Blocking api.openai.com/v1/embeddings in DevTools is one option."
record_check 'BM25 results remain visible.'
record_check 'The UI says `Semantic search unavailable. Showing keyword results.`'
step "Restore the key or network rule and run one more different query."
record_check 'The completed search reports `Hybrid` again.'

stage "Release completion"
open_before=$(count_open_before_completion)
if [[ "$open_before" -eq 0 ]]; then
  mark_checkbox "Every check above passes in the production build."
  log_result PASS "Every check above passes in the production build."
else
  warn "$open_before acceptance check(s) before Completion are still open."
  log_result OPEN "$open_before acceptance check(s) before Completion"
fi
record_check 'The observed OpenAI request counts match the privacy descriptions in README.'
if [[ "$FAILURES" -eq 0 ]]; then
  mark_checkbox "Any deviation has a linked blocking issue."
  log_result PASS "Any deviation has a linked blocking issue. No deviations recorded."
else
  ask BLOCKING_ISSUES "Paste comma-separated blocking issue URL(s), or leave blank:"
  if [[ "$BLOCKING_ISSUES" =~ ^https?:// ]]; then
    mark_checkbox "Any deviation has a linked blocking issue."
    log_result PASS "Any deviation has a linked blocking issue." "$BLOCKING_ISSUES"
  else
    warn "Failures were recorded without a blocking issue URL."
    log_result OPEN "Any deviation has a linked blocking issue."
  fi
fi

remaining=$(grep -c '^- \[ \]' "$CHECKLIST_FILE" || true)
printf '\n'
if [[ "$remaining" -eq 0 ]]; then
  say "All checklist items are complete."
else
  warn "$remaining checklist item(s) remain open. Re-run the wizard after addressing them."
fi
say "Checklist: $CHECKLIST_FILE"
say "Evidence log: $RESULTS_FILE"

finish
